version: '3.7'
services:
  nginx:
    image: nginx
    environment:
      - SERVER_PORT=80
      - SERVER_NAME=127.0.0.1
    command: /bin/sh -c "envsubst '$$SERVER_PORT $$SERVER_NAME' < /etc/nginx/configuration/admitad.conf > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    ports:
      - "8028:80"
    volumes:
      - .:/var/www
      - ./docker/nginx:/etc/nginx/configuration
    depends_on:
      - php
  php:
    build:
      context: ./docker/php
    volumes:
      - .:/var/www
      - ./docker/php/admitad.conf:/etc/php7/php-fpm.d/www.conf
      - ./docker/php/app.ini:/etc/php7/conf.d/app.ini
    working_dir: /var/www
  postgres:
    image: postgres:12.2-alpine
    environment:
      - POSTGRES_USER=admitad
      - POSTGRES_PASSWORD=admitad
      - POSTGRES_DB=admitad
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - postgres_data:/var/lib/postgresql/data/pgdata
    ports:
      - "5684:5432"
volumes:
  postgres_data:
    driver: local
    driver_opts:
      type: none
      device: $PWD/docker/data/pgdata
      o: bind
networks:
  default:
    external:
      name: admitad-test